Module Module1
    Public Function BCDconvert(s As String) As Byte
        Dim temp, temp1, temp2 As Byte
        Dim s1, s2 As String
        s1 = Right(s, 1)
        s2 = Left(s, 1)
        temp1 = Val(s1)
        temp2 = Val(s2)
        temp = temp1 + (temp2 * 16)


        BCDconvert = temp
    End Function

    Public Sub SaveDefaults()
        Dim file As System.IO.StreamWriter
        file = My.Computer.FileSystem.OpenTextFileWriter("defaults.squ", False)
        file.WriteLine(MainForm.NomeSX.Text)
        file.WriteLine(MainForm.NumeroSX1.Text)
        file.WriteLine(MainForm.NomeSX1.Text)
        file.WriteLine(MainForm.NumeroSX2.Text)
        file.WriteLine(MainForm.NomeSX2.Text)
        file.WriteLine(MainForm.NumeroSX3.Text)
        file.WriteLine(MainForm.NomeSX3.Text)
        file.WriteLine(MainForm.NumeroSX4.Text)
        file.WriteLine(MainForm.NomeSX4.Text)
        file.WriteLine(MainForm.NumeroSX5.Text)
        file.WriteLine(MainForm.NomeSX5.Text)
        file.WriteLine(MainForm.NumeroSX6.Text)
        file.WriteLine(MainForm.NomeSX6.Text)
        file.WriteLine(MainForm.NumeroSX7.Text)
        file.WriteLine(MainForm.NomeSX7.Text)
        file.WriteLine(MainForm.NumeroSX8.Text)
        file.WriteLine(MainForm.NomeSX8.Text)
        file.WriteLine(MainForm.NumeroSX9.Text)
        file.WriteLine(MainForm.NomeSX9.Text)
        file.WriteLine(MainForm.NumeroSX10.Text)
        file.WriteLine(MainForm.NomeSX10.Text)
        file.WriteLine(MainForm.NumeroSX11.Text)
        file.WriteLine(MainForm.NomeSX11.Text)
        file.WriteLine(MainForm.NumeroSX12.Text)
        file.WriteLine(MainForm.NomeSX12.Text)

        file.WriteLine(MainForm.NomeDX.Text)
        file.WriteLine(MainForm.NumeroDX1.Text)
        file.WriteLine(MainForm.NomeDX1.Text)
        file.WriteLine(MainForm.NumeroDX2.Text)
        file.WriteLine(MainForm.NomeDX2.Text)
        file.WriteLine(MainForm.NumeroDX3.Text)
        file.WriteLine(MainForm.NomeDX3.Text)
        file.WriteLine(MainForm.NumeroDX4.Text)
        file.WriteLine(MainForm.NomeDX4.Text)
        file.WriteLine(MainForm.NumeroDX5.Text)
        file.WriteLine(MainForm.NomeDX5.Text)
        file.WriteLine(MainForm.NumeroDX6.Text)
        file.WriteLine(MainForm.NomeDX6.Text)
        file.WriteLine(MainForm.NumeroDX7.Text)
        file.WriteLine(MainForm.NomeDX7.Text)
        file.WriteLine(MainForm.NumeroDX8.Text)
        file.WriteLine(MainForm.NomeDX8.Text)
        file.WriteLine(MainForm.NumeroDX9.Text)
        file.WriteLine(MainForm.NomeDX9.Text)
        file.WriteLine(MainForm.NumeroDX10.Text)
        file.WriteLine(MainForm.NomeDX10.Text)
        file.WriteLine(MainForm.NumeroDX11.Text)
        file.WriteLine(MainForm.NomeDX11.Text)
        file.WriteLine(MainForm.NumeroDX12.Text)
        file.WriteLine(MainForm.NomeDX12.Text)

        file.Close()
    End Sub

    Public Sub LoadDefaults()
        Dim file As System.IO.StreamReader
        Try
            file = My.Computer.FileSystem.OpenTextFileReader("defaults.squ")

            MainForm.NomeSX.Text = file.ReadLine()
            MainForm.NumeroSX1.Text = file.ReadLine()
            MainForm.NomeSX1.Text = file.ReadLine()
            MainForm.NumeroSX2.Text = file.ReadLine()
            MainForm.NomeSX2.Text = file.ReadLine()
            MainForm.NumeroSX3.Text = file.ReadLine()
            MainForm.NomeSX3.Text = file.ReadLine()
            MainForm.NumeroSX4.Text = file.ReadLine()
            MainForm.NomeSX4.Text = file.ReadLine()
            MainForm.NumeroSX5.Text = file.ReadLine()
            MainForm.NomeSX5.Text = file.ReadLine()
            MainForm.NumeroSX6.Text = file.ReadLine()
            MainForm.NomeSX6.Text = file.ReadLine()
            MainForm.NumeroSX7.Text = file.ReadLine()
            MainForm.NomeSX7.Text = file.ReadLine()
            MainForm.NumeroSX8.Text = file.ReadLine()
            MainForm.NomeSX8.Text = file.ReadLine()
            MainForm.NumeroSX9.Text = file.ReadLine()
            MainForm.NomeSX9.Text = file.ReadLine()
            MainForm.NumeroSX10.Text = file.ReadLine()
            MainForm.NomeSX10.Text = file.ReadLine()
            MainForm.NumeroSX11.Text = file.ReadLine()
            MainForm.NomeSX11.Text = file.ReadLine()
            MainForm.NumeroSX12.Text = file.ReadLine()
            MainForm.NomeSX12.Text = file.ReadLine()

            MainForm.NomeDX.Text = file.ReadLine()
            MainForm.NumeroDX1.Text = file.ReadLine()
            MainForm.NomeDX1.Text = file.ReadLine()
            MainForm.NumeroDX2.Text = file.ReadLine()
            MainForm.NomeDX2.Text = file.ReadLine()
            MainForm.NumeroDX3.Text = file.ReadLine()
            MainForm.NomeDX3.Text = file.ReadLine()
            MainForm.NumeroDX4.Text = file.ReadLine()
            MainForm.NomeDX4.Text = file.ReadLine()
            MainForm.NumeroDX5.Text = file.ReadLine()
            MainForm.NomeDX5.Text = file.ReadLine()
            MainForm.NumeroDX6.Text = file.ReadLine()
            MainForm.NomeDX6.Text = file.ReadLine()
            MainForm.NumeroDX7.Text = file.ReadLine()
            MainForm.NomeDX7.Text = file.ReadLine()
            MainForm.NumeroDX8.Text = file.ReadLine()
            MainForm.NomeDX8.Text = file.ReadLine()
            MainForm.NumeroDX9.Text = file.ReadLine()
            MainForm.NomeDX9.Text = file.ReadLine()
            MainForm.NumeroDX10.Text = file.ReadLine()
            MainForm.NomeDX10.Text = file.ReadLine()
            MainForm.NumeroDX11.Text = file.ReadLine()
            MainForm.NomeDX11.Text = file.ReadLine()
            MainForm.NumeroDX12.Text = file.ReadLine()
            MainForm.NomeDX12.Text = file.ReadLine()
        Catch
        End Try
    End Sub
End Module
